{% set name = "pyerfa" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8572fd24ac779f067209dce1f2f6996d0701359724ecb89422ceb431632d554
  patches:
    - patches/0001-avoid-redefining-typeobject-pypy.patch

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - pip
    - setuptools_scm
    - jinja2 >=2.10.3
    - python
    - numpy
    - packaging
  run:
    - python
    - {{ pin_compatible("numpy") }}

test:
  imports:
    - erfa


about:
  home: https://pyerfa.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Python bindings for ERFA routines
  description: |
    PyERFA is the Python wrapper for the ERFA library (Essential Routines for
    Fundamental Astronomy), a C library containing key algorithms for astronomy,
    which is based on the SOFA library published by the International
    Astronomical Union (IAU). All C routines are wrapped as Numpy universal
    functions, so that they can be called with scalar or array inputs.

    The project is a split of astropy._erfa module, developed in the context of
    Astropy project, into a standalone package. It contains the ERFA C source
    code as a git submodule. The wrapping is done with help of the Jinja2
    template engine.
  doc_url: https://pyerfa.readthedocs.io/
  dev_url: https://github.com/liberfa/pyerfa

extra:
  recipe-maintainers:
    - mwcraig
    - astrofrog
    - avalentino
